apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-health
  namespace: argocd
spec:
  destination:
    namespace: spring-health
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev
    repoURL: https://github.com/kwbach/springboot_health_config.git
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application     
