apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-java-app
spec:
  params:
  - name: buildRevision
  - name: appGitUrl
  - name: appImage
  workspaces:
  - name: app-source

  steps:
    - 
  - name: build-sources
    image: sdaschner/maven-jdk14:quarkus-deps-1.5.1-b5
    workingDir: "$(workspaces.app-source.path)/app"
    command:
    - /usr/bin/mvn
    args:
    - clean
    - package

  - name: build-image
    image: quay.io/buildah/stable
    workingDir: "$(workspaces.app-source.path)/app"
    command: ['buildah', 'bud', '--tls-verify=false', '--layers', '-f', 'Dockerfile', '-t', '$(params.appImage):$(params.buildRevision)', '.']
    volumeMounts:
    - name: varlibc
      mountPath: /var/lib/containers
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 0
      privileged: true

  - name: build-push
    image: quay.io/buildah/stable
    command: ["buildah", "push", "--tls-verify=false", "$(params.appImage):$(params.buildRevision)", "docker://$(params.appImage):$(params.buildRevision)"]
    volumeMounts:
    - name: varlibc
      mountPath: /var/lib/containers
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 0
      privileged: true

  volumes:
  - name: varlibc
    emptyDir: {}
---
